version: '3.9'
services:
  db:
    container_name: db
    image: mariadb:latest
    expose:
      - 3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_USER: "kleiderkammer"
      MARIADB_PASSWORD: "kleiderkammer"
      MARIADB_DATABASE: "kleiderkammer"

  flask:
    container_name: flask
    image: michelblank/kleiderkammer:latest
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      FLASK_SECRET_KEY: "SomethingNotEntirelySecret"
      FLASK_TESTING: "True"
      FLASK_DEBUG: "True"
      FLASK_OIDC_CLIENT_SECRETS__WEB__CLIENT_ID: "studium-webtechnologie-seminararbeit"
      FLASK_OIDC_CLIENT_SECRETS__WEB__CLIENT_SECRET: "..."
      FLASK_OIDC_CLIENT_SECRETS__WEB__AUTH_URI: "https://idp.michelblank.de/auth/realms/BlankIDP/protocol/openid-connect/auth"
      FLASK_OIDC_CLIENT_SECRETS__WEB__TOKEN_URI: "https://idp.michelblank.de/auth/realms/BlankIDP/protocol/openid-connect/token"
      FLASK_OIDC_CLIENT_SECRETS__WEB__ISSUER: "https://idp.michelblank.de/auth/realms/BlankIDP"
      FLASK_OIDC_CLIENT_SECRETS__WEB__USERINFO_URI: "https://idp.michelblank.de/auth/realms/BlankIDP/protocol/openid-connect/userinfo"
      FLASK_OIDC_CLIENT_SECRETS__WEB__TOKEN_INTROSPECTION_URI: "https://idp.michelblank.de/auth/realms/BlankIDP/protocol/openid-connect/token/introspect"
      FLASK_OIDC_ID_TOKEN_COOKIE_SECURE: "False"
      FLASK_OIDC_REQUIRE_VERIFIED_EMAIL: "False"
      FLASK_OIDC_OPENID_REALM: "http://localhost:5000/oidc_callback"
      FLASK_OIDC_SCOPES: "openid"
      FLASK_OIDC_COOKIE_SECURE: "False"
      FLASK_SQLALCHEMY_DATABASE_URI: "mysql://kleiderkammer:kleiderkammer@db:3306/kleiderkammer"
      FLASK_SQLALCHEMY_TRACK_MODIFICATIONS: "False"
    expose:
      - 5000
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    links:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80/tcp"

volumes:
  database:
    name: "kleiderkammer-db"