version: '3.9'
services:
  db:
    container_name: db
    image: mariadb:latest
    expose:
      - 3306
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: kleiderkammer

  flask:
    container_name: flask
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./client_secrets.json:/app/client_secrets.json:ro
    expose:
      - 5000
    links:
      - db
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    links:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80/tcp"